# Generated by Django 5.2.4 on 2025-07-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Mô tả SEO (để trống sẽ dùng mô tả sản phẩm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Từ khóa SEO (phân cách bằng dấu phẩy)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề SEO (để trống sẽ dùng tên sản phẩm)', max_length=200),
        ),
    ]
