# Generated by Django 5.2.4 on 2025-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_meta_description_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'name'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Thứ tự hiển thị (0=off, 1=đầu tiên, 2=thứ hai, ...)'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hiển thị danh mục này?'),
        ),
    ]
